# 常数
RANDOM_STATE = 42
TEST_SIZE = 0.2
# 树模型默认训练参数
TREE_DEFAULT_NUM_BOOST_ROUND = 2000
TREE_DEFAULT_EARLY_STOPPING_ROUND = 50
TREE_DEFAULT_N_TRIALS = 5000
TREE_N_JOBS = 10
# 深度模型默认训练参数
TB_DEFAULT_BATCH_SIZE = 256
TB_DEFAULT_MAX_EPOCHS = 100
TB_DEFAULT_N_TRIALS = 50
TB_N_JOBS = 1
